---
- name: Deploy influxdb to monitoring server
  hosts: monitoring
  become: true
  gather_facts: False
  vars_files:
    - "vars/main.yml"
  tasks:
    - name: Assures directories exists
      file: path="{{item}}" state=directory
      with_items:
        - "/var/log/fluentd"
        - "/etc/fluent"
      tags:
        - fluentd

    - name: Copy configurations
      template: src="config/fluentd/fluent.conf"
                dest="/etc/fluent/fluent.conf"
                owner=root
                group=root
      tags:
        - fluentd

    - name: "Pull fluentd docker image"
      docker_image:
        state: present
        name: "fluent/fluentd:1.3.1"
        tag: "1.3.1"
      tags:
        - fluentd

    - name: "Launch fluentd container"
      docker_container:
        name: fluentd
        image: "fluent/fluentd:1.3.1"
        state: started
        restart_policy: always
        volumes:
          - /var/log/fluentd:/fluentd/log
          - /etc/fluent:/fluentd/etc
        ports:
          - "24224:24224"
          - "24224:24224/udp"
        environment:
          FLUENTD_CONF: fluent.conf
        networks:
          - name: "{{ app_network_name }}"
      tags:
        - fluentd
